[book]
authors = ["Nate Wilcox"]
language = "en"
multilingual = false
src = "src"
title = "ğŸ›¡ï¸NateğŸ›¡ï¸"

[build]
build-dir = "./docs"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
